[program:indiserver]
autostart = true
autorestart = true
command = /usr/bin/indiserver -v indi_vantage_weather
user = pi
stdout_logfile = /home/pi/indiserver.log
stderr_logfile = /home/pi/indiserver.err

[program:indi2mqtt]
autostart = true
autorestart = true
directory = /home/pi/indi2mqtt/build
command = /home/pi/indi2mqtt/build/indi2mqtt
stdout_logfile = /home/pi/indi2mqtt.log
stderr_logfile = /home/pi/indi2mqtt.err
user = pi
