[program:ecowitt2mqtt]
autostart = true
autorestart = true
command = /home/pi/MoonRabbit/venv/bin/ecowitt2mqtt
    --mqtt-broker=localhost
    --mqtt-port=1883
    --mqtt-topic=ecowitt
    --input-data-format=ecowitt
    --port=8080
stdout_logfile = /home/pi/ecowitt2mqtt.log
stderr_logfile = /home/pi/ecowitt2mqtt.err
user = pi
