# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _PyIndi
else:
    import _PyIndi

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _PyIndi.delete_SwigPyIterator

    def value(self):
        return _PyIndi.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _PyIndi.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _PyIndi.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _PyIndi.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _PyIndi.SwigPyIterator_equal(self, x)

    def copy(self):
        return _PyIndi.SwigPyIterator_copy(self)

    def next(self):
        return _PyIndi.SwigPyIterator_next(self)

    def __next__(self):
        return _PyIndi.SwigPyIterator___next__(self)

    def previous(self):
        return _PyIndi.SwigPyIterator_previous(self)

    def advance(self, n):
        return _PyIndi.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _PyIndi.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _PyIndi.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _PyIndi.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _PyIndi.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _PyIndi.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _PyIndi.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _PyIndi:
_PyIndi.SwigPyIterator_swigregister(SwigPyIterator)
class BaseDeviceVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _PyIndi.BaseDeviceVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _PyIndi.BaseDeviceVector___nonzero__(self)

    def __bool__(self):
        return _PyIndi.BaseDeviceVector___bool__(self)

    def __len__(self):
        return _PyIndi.BaseDeviceVector___len__(self)

    def __getslice__(self, i, j):
        return _PyIndi.BaseDeviceVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _PyIndi.BaseDeviceVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _PyIndi.BaseDeviceVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _PyIndi.BaseDeviceVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _PyIndi.BaseDeviceVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _PyIndi.BaseDeviceVector___setitem__(self, *args)

    def pop(self):
        return _PyIndi.BaseDeviceVector_pop(self)

    def append(self, x):
        return _PyIndi.BaseDeviceVector_append(self, x)

    def empty(self):
        return _PyIndi.BaseDeviceVector_empty(self)

    def size(self):
        return _PyIndi.BaseDeviceVector_size(self)

    def swap(self, v):
        return _PyIndi.BaseDeviceVector_swap(self, v)

    def begin(self):
        return _PyIndi.BaseDeviceVector_begin(self)

    def end(self):
        return _PyIndi.BaseDeviceVector_end(self)

    def rbegin(self):
        return _PyIndi.BaseDeviceVector_rbegin(self)

    def rend(self):
        return _PyIndi.BaseDeviceVector_rend(self)

    def clear(self):
        return _PyIndi.BaseDeviceVector_clear(self)

    def get_allocator(self):
        return _PyIndi.BaseDeviceVector_get_allocator(self)

    def pop_back(self):
        return _PyIndi.BaseDeviceVector_pop_back(self)

    def erase(self, *args):
        return _PyIndi.BaseDeviceVector_erase(self, *args)

    def __init__(self, *args):
        _PyIndi.BaseDeviceVector_swiginit(self, _PyIndi.new_BaseDeviceVector(*args))

    def push_back(self, x):
        return _PyIndi.BaseDeviceVector_push_back(self, x)

    def front(self):
        return _PyIndi.BaseDeviceVector_front(self)

    def back(self):
        return _PyIndi.BaseDeviceVector_back(self)

    def assign(self, n, x):
        return _PyIndi.BaseDeviceVector_assign(self, n, x)

    def resize(self, *args):
        return _PyIndi.BaseDeviceVector_resize(self, *args)

    def insert(self, *args):
        return _PyIndi.BaseDeviceVector_insert(self, *args)

    def reserve(self, n):
        return _PyIndi.BaseDeviceVector_reserve(self, n)

    def capacity(self):
        return _PyIndi.BaseDeviceVector_capacity(self)
    __swig_destroy__ = _PyIndi.delete_BaseDeviceVector

# Register BaseDeviceVector in _PyIndi:
_PyIndi.BaseDeviceVector_swigregister(BaseDeviceVector)
class PropertyVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _PyIndi.PropertyVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _PyIndi.PropertyVector___nonzero__(self)

    def __bool__(self):
        return _PyIndi.PropertyVector___bool__(self)

    def __len__(self):
        return _PyIndi.PropertyVector___len__(self)

    def __getslice__(self, i, j):
        return _PyIndi.PropertyVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _PyIndi.PropertyVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _PyIndi.PropertyVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _PyIndi.PropertyVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _PyIndi.PropertyVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _PyIndi.PropertyVector___setitem__(self, *args)

    def pop(self):
        return _PyIndi.PropertyVector_pop(self)

    def append(self, x):
        return _PyIndi.PropertyVector_append(self, x)

    def empty(self):
        return _PyIndi.PropertyVector_empty(self)

    def size(self):
        return _PyIndi.PropertyVector_size(self)

    def swap(self, v):
        return _PyIndi.PropertyVector_swap(self, v)

    def begin(self):
        return _PyIndi.PropertyVector_begin(self)

    def end(self):
        return _PyIndi.PropertyVector_end(self)

    def rbegin(self):
        return _PyIndi.PropertyVector_rbegin(self)

    def rend(self):
        return _PyIndi.PropertyVector_rend(self)

    def clear(self):
        return _PyIndi.PropertyVector_clear(self)

    def get_allocator(self):
        return _PyIndi.PropertyVector_get_allocator(self)

    def pop_back(self):
        return _PyIndi.PropertyVector_pop_back(self)

    def erase(self, *args):
        return _PyIndi.PropertyVector_erase(self, *args)

    def __init__(self, *args):
        _PyIndi.PropertyVector_swiginit(self, _PyIndi.new_PropertyVector(*args))

    def push_back(self, x):
        return _PyIndi.PropertyVector_push_back(self, x)

    def front(self):
        return _PyIndi.PropertyVector_front(self)

    def back(self):
        return _PyIndi.PropertyVector_back(self)

    def assign(self, n, x):
        return _PyIndi.PropertyVector_assign(self, n, x)

    def resize(self, *args):
        return _PyIndi.PropertyVector_resize(self, *args)

    def insert(self, *args):
        return _PyIndi.PropertyVector_insert(self, *args)

    def reserve(self, n):
        return _PyIndi.PropertyVector_reserve(self, n)

    def capacity(self):
        return _PyIndi.PropertyVector_capacity(self)
    __swig_destroy__ = _PyIndi.delete_PropertyVector

# Register PropertyVector in _PyIndi:
_PyIndi.PropertyVector_swigregister(PropertyVector)
INDI_NUMBER = _PyIndi.INDI_NUMBER
INDI_SWITCH = _PyIndi.INDI_SWITCH
INDI_TEXT = _PyIndi.INDI_TEXT
INDI_LIGHT = _PyIndi.INDI_LIGHT
INDI_BLOB = _PyIndi.INDI_BLOB
INDI_UNKNOWN = _PyIndi.INDI_UNKNOWN
AXIS_RA = _PyIndi.AXIS_RA
AXIS_DE = _PyIndi.AXIS_DE
AXIS_AZ = _PyIndi.AXIS_AZ
AXIS_ALT = _PyIndi.AXIS_ALT
DIRECTION_NORTH = _PyIndi.DIRECTION_NORTH
DIRECTION_SOUTH = _PyIndi.DIRECTION_SOUTH
DIRECTION_WEST = _PyIndi.DIRECTION_WEST
DIRECTION_EAST = _PyIndi.DIRECTION_EAST
INDI_DEVICE_NOT_FOUND = _PyIndi.INDI_DEVICE_NOT_FOUND
INDI_PROPERTY_INVALID = _PyIndi.INDI_PROPERTY_INVALID
INDI_PROPERTY_DUPLICATED = _PyIndi.INDI_PROPERTY_DUPLICATED
INDI_DISPATCH_ERROR = _PyIndi.INDI_DISPATCH_ERROR
INDI_MONO = _PyIndi.INDI_MONO
INDI_BAYER_RGGB = _PyIndi.INDI_BAYER_RGGB
INDI_BAYER_GRBG = _PyIndi.INDI_BAYER_GRBG
INDI_BAYER_GBRG = _PyIndi.INDI_BAYER_GBRG
INDI_BAYER_BGGR = _PyIndi.INDI_BAYER_BGGR
INDI_BAYER_CYYM = _PyIndi.INDI_BAYER_CYYM
INDI_BAYER_YCMY = _PyIndi.INDI_BAYER_YCMY
INDI_BAYER_YMCY = _PyIndi.INDI_BAYER_YMCY
INDI_BAYER_MYYC = _PyIndi.INDI_BAYER_MYYC
INDI_RGB = _PyIndi.INDI_RGB
INDI_BGR = _PyIndi.INDI_BGR
INDI_JPG = _PyIndi.INDI_JPG
INDIV = _PyIndi.INDIV
INDI_VERSION_MAJOR = _PyIndi.INDI_VERSION_MAJOR
INDI_VERSION_MINOR = _PyIndi.INDI_VERSION_MINOR
INDI_VERSION_RELEASE = _PyIndi.INDI_VERSION_RELEASE
ISS_OFF = _PyIndi.ISS_OFF
ISS_ON = _PyIndi.ISS_ON
IPS_IDLE = _PyIndi.IPS_IDLE
IPS_OK = _PyIndi.IPS_OK
IPS_BUSY = _PyIndi.IPS_BUSY
IPS_ALERT = _PyIndi.IPS_ALERT
ISR_1OFMANY = _PyIndi.ISR_1OFMANY
ISR_ATMOST1 = _PyIndi.ISR_ATMOST1
ISR_NOFMANY = _PyIndi.ISR_NOFMANY
IP_RO = _PyIndi.IP_RO
IP_WO = _PyIndi.IP_WO
IP_RW = _PyIndi.IP_RW
MAXINDINAME = _PyIndi.MAXINDINAME
MAXINDILABEL = _PyIndi.MAXINDILABEL
MAXINDIDEVICE = _PyIndi.MAXINDIDEVICE
MAXINDIGROUP = _PyIndi.MAXINDIGROUP
MAXINDIFORMAT = _PyIndi.MAXINDIFORMAT
MAXINDIBLOBFMT = _PyIndi.MAXINDIBLOBFMT
MAXINDITSTAMP = _PyIndi.MAXINDITSTAMP
MAXINDIMESSAGE = _PyIndi.MAXINDIMESSAGE
class IText(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    name = property(_PyIndi.IText_name_get, _PyIndi.IText_name_set)
    label = property(_PyIndi.IText_label_get, _PyIndi.IText_label_set)
    text = property(_PyIndi.IText_text_get, _PyIndi.IText_text_set)
    tvp = property(_PyIndi.IText_tvp_get, _PyIndi.IText_tvp_set)
    aux0 = property(_PyIndi.IText_aux0_get, _PyIndi.IText_aux0_set)
    aux1 = property(_PyIndi.IText_aux1_get, _PyIndi.IText_aux1_set)

    def __init__(self):
        _PyIndi.IText_swiginit(self, _PyIndi.new_IText())
    __swig_destroy__ = _PyIndi.delete_IText

# Register IText in _PyIndi:
_PyIndi.IText_swigregister(IText)
class ITextVectorProperty(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    device = property(_PyIndi.ITextVectorProperty_device_get, _PyIndi.ITextVectorProperty_device_set)
    name = property(_PyIndi.ITextVectorProperty_name_get, _PyIndi.ITextVectorProperty_name_set)
    label = property(_PyIndi.ITextVectorProperty_label_get, _PyIndi.ITextVectorProperty_label_set)
    group = property(_PyIndi.ITextVectorProperty_group_get, _PyIndi.ITextVectorProperty_group_set)
    p = property(_PyIndi.ITextVectorProperty_p_get, _PyIndi.ITextVectorProperty_p_set)
    timeout = property(_PyIndi.ITextVectorProperty_timeout_get, _PyIndi.ITextVectorProperty_timeout_set)
    s = property(_PyIndi.ITextVectorProperty_s_get, _PyIndi.ITextVectorProperty_s_set)
    tp = property(_PyIndi.ITextVectorProperty_tp_get, _PyIndi.ITextVectorProperty_tp_set)
    ntp = property(_PyIndi.ITextVectorProperty_ntp_get, _PyIndi.ITextVectorProperty_ntp_set)
    timestamp = property(_PyIndi.ITextVectorProperty_timestamp_get, _PyIndi.ITextVectorProperty_timestamp_set)
    aux = property(_PyIndi.ITextVectorProperty_aux_get, _PyIndi.ITextVectorProperty_aux_set)

    def __getitem__(self, index):
        return _PyIndi.ITextVectorProperty___getitem__(self, index)

    def __len__(self):
        return _PyIndi.ITextVectorProperty___len__(self)

    def __init__(self):
        _PyIndi.ITextVectorProperty_swiginit(self, _PyIndi.new_ITextVectorProperty())
    __swig_destroy__ = _PyIndi.delete_ITextVectorProperty

# Register ITextVectorProperty in _PyIndi:
_PyIndi.ITextVectorProperty_swigregister(ITextVectorProperty)
class INumber(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    name = property(_PyIndi.INumber_name_get, _PyIndi.INumber_name_set)
    label = property(_PyIndi.INumber_label_get, _PyIndi.INumber_label_set)
    format = property(_PyIndi.INumber_format_get, _PyIndi.INumber_format_set)
    min = property(_PyIndi.INumber_min_get, _PyIndi.INumber_min_set)
    max = property(_PyIndi.INumber_max_get, _PyIndi.INumber_max_set)
    step = property(_PyIndi.INumber_step_get, _PyIndi.INumber_step_set)
    value = property(_PyIndi.INumber_value_get, _PyIndi.INumber_value_set)
    nvp = property(_PyIndi.INumber_nvp_get, _PyIndi.INumber_nvp_set)
    aux0 = property(_PyIndi.INumber_aux0_get, _PyIndi.INumber_aux0_set)
    aux1 = property(_PyIndi.INumber_aux1_get, _PyIndi.INumber_aux1_set)

    def __init__(self):
        _PyIndi.INumber_swiginit(self, _PyIndi.new_INumber())
    __swig_destroy__ = _PyIndi.delete_INumber

# Register INumber in _PyIndi:
_PyIndi.INumber_swigregister(INumber)
class INumberVectorProperty(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    device = property(_PyIndi.INumberVectorProperty_device_get, _PyIndi.INumberVectorProperty_device_set)
    name = property(_PyIndi.INumberVectorProperty_name_get, _PyIndi.INumberVectorProperty_name_set)
    label = property(_PyIndi.INumberVectorProperty_label_get, _PyIndi.INumberVectorProperty_label_set)
    group = property(_PyIndi.INumberVectorProperty_group_get, _PyIndi.INumberVectorProperty_group_set)
    p = property(_PyIndi.INumberVectorProperty_p_get, _PyIndi.INumberVectorProperty_p_set)
    timeout = property(_PyIndi.INumberVectorProperty_timeout_get, _PyIndi.INumberVectorProperty_timeout_set)
    s = property(_PyIndi.INumberVectorProperty_s_get, _PyIndi.INumberVectorProperty_s_set)
    np = property(_PyIndi.INumberVectorProperty_np_get, _PyIndi.INumberVectorProperty_np_set)
    nnp = property(_PyIndi.INumberVectorProperty_nnp_get, _PyIndi.INumberVectorProperty_nnp_set)
    timestamp = property(_PyIndi.INumberVectorProperty_timestamp_get, _PyIndi.INumberVectorProperty_timestamp_set)
    aux = property(_PyIndi.INumberVectorProperty_aux_get, _PyIndi.INumberVectorProperty_aux_set)

    def __getitem__(self, index):
        return _PyIndi.INumberVectorProperty___getitem__(self, index)

    def __len__(self):
        return _PyIndi.INumberVectorProperty___len__(self)

    def __init__(self):
        _PyIndi.INumberVectorProperty_swiginit(self, _PyIndi.new_INumberVectorProperty())
    __swig_destroy__ = _PyIndi.delete_INumberVectorProperty

# Register INumberVectorProperty in _PyIndi:
_PyIndi.INumberVectorProperty_swigregister(INumberVectorProperty)
class ISwitch(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    name = property(_PyIndi.ISwitch_name_get, _PyIndi.ISwitch_name_set)
    label = property(_PyIndi.ISwitch_label_get, _PyIndi.ISwitch_label_set)
    s = property(_PyIndi.ISwitch_s_get, _PyIndi.ISwitch_s_set)
    svp = property(_PyIndi.ISwitch_svp_get, _PyIndi.ISwitch_svp_set)
    aux = property(_PyIndi.ISwitch_aux_get, _PyIndi.ISwitch_aux_set)

    def __init__(self):
        _PyIndi.ISwitch_swiginit(self, _PyIndi.new_ISwitch())
    __swig_destroy__ = _PyIndi.delete_ISwitch

# Register ISwitch in _PyIndi:
_PyIndi.ISwitch_swigregister(ISwitch)
class ISwitchVectorProperty(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    device = property(_PyIndi.ISwitchVectorProperty_device_get, _PyIndi.ISwitchVectorProperty_device_set)
    name = property(_PyIndi.ISwitchVectorProperty_name_get, _PyIndi.ISwitchVectorProperty_name_set)
    label = property(_PyIndi.ISwitchVectorProperty_label_get, _PyIndi.ISwitchVectorProperty_label_set)
    group = property(_PyIndi.ISwitchVectorProperty_group_get, _PyIndi.ISwitchVectorProperty_group_set)
    p = property(_PyIndi.ISwitchVectorProperty_p_get, _PyIndi.ISwitchVectorProperty_p_set)
    r = property(_PyIndi.ISwitchVectorProperty_r_get, _PyIndi.ISwitchVectorProperty_r_set)
    timeout = property(_PyIndi.ISwitchVectorProperty_timeout_get, _PyIndi.ISwitchVectorProperty_timeout_set)
    s = property(_PyIndi.ISwitchVectorProperty_s_get, _PyIndi.ISwitchVectorProperty_s_set)
    sp = property(_PyIndi.ISwitchVectorProperty_sp_get, _PyIndi.ISwitchVectorProperty_sp_set)
    nsp = property(_PyIndi.ISwitchVectorProperty_nsp_get, _PyIndi.ISwitchVectorProperty_nsp_set)
    timestamp = property(_PyIndi.ISwitchVectorProperty_timestamp_get, _PyIndi.ISwitchVectorProperty_timestamp_set)
    aux = property(_PyIndi.ISwitchVectorProperty_aux_get, _PyIndi.ISwitchVectorProperty_aux_set)

    def __getitem__(self, index):
        return _PyIndi.ISwitchVectorProperty___getitem__(self, index)

    def __len__(self):
        return _PyIndi.ISwitchVectorProperty___len__(self)

    def __init__(self):
        _PyIndi.ISwitchVectorProperty_swiginit(self, _PyIndi.new_ISwitchVectorProperty())
    __swig_destroy__ = _PyIndi.delete_ISwitchVectorProperty

# Register ISwitchVectorProperty in _PyIndi:
_PyIndi.ISwitchVectorProperty_swigregister(ISwitchVectorProperty)
class ILight(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    name = property(_PyIndi.ILight_name_get, _PyIndi.ILight_name_set)
    label = property(_PyIndi.ILight_label_get, _PyIndi.ILight_label_set)
    s = property(_PyIndi.ILight_s_get, _PyIndi.ILight_s_set)
    lvp = property(_PyIndi.ILight_lvp_get, _PyIndi.ILight_lvp_set)
    aux = property(_PyIndi.ILight_aux_get, _PyIndi.ILight_aux_set)

    def __init__(self):
        _PyIndi.ILight_swiginit(self, _PyIndi.new_ILight())
    __swig_destroy__ = _PyIndi.delete_ILight

# Register ILight in _PyIndi:
_PyIndi.ILight_swigregister(ILight)
class ILightVectorProperty(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    device = property(_PyIndi.ILightVectorProperty_device_get, _PyIndi.ILightVectorProperty_device_set)
    name = property(_PyIndi.ILightVectorProperty_name_get, _PyIndi.ILightVectorProperty_name_set)
    label = property(_PyIndi.ILightVectorProperty_label_get, _PyIndi.ILightVectorProperty_label_set)
    group = property(_PyIndi.ILightVectorProperty_group_get, _PyIndi.ILightVectorProperty_group_set)
    s = property(_PyIndi.ILightVectorProperty_s_get, _PyIndi.ILightVectorProperty_s_set)
    lp = property(_PyIndi.ILightVectorProperty_lp_get, _PyIndi.ILightVectorProperty_lp_set)
    nlp = property(_PyIndi.ILightVectorProperty_nlp_get, _PyIndi.ILightVectorProperty_nlp_set)
    timestamp = property(_PyIndi.ILightVectorProperty_timestamp_get, _PyIndi.ILightVectorProperty_timestamp_set)
    aux = property(_PyIndi.ILightVectorProperty_aux_get, _PyIndi.ILightVectorProperty_aux_set)

    def __getitem__(self, index):
        return _PyIndi.ILightVectorProperty___getitem__(self, index)

    def __len__(self):
        return _PyIndi.ILightVectorProperty___len__(self)

    def __init__(self):
        _PyIndi.ILightVectorProperty_swiginit(self, _PyIndi.new_ILightVectorProperty())
    __swig_destroy__ = _PyIndi.delete_ILightVectorProperty

# Register ILightVectorProperty in _PyIndi:
_PyIndi.ILightVectorProperty_swigregister(ILightVectorProperty)
class IBLOB(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    name = property(_PyIndi.IBLOB_name_get, _PyIndi.IBLOB_name_set)
    label = property(_PyIndi.IBLOB_label_get, _PyIndi.IBLOB_label_set)
    format = property(_PyIndi.IBLOB_format_get, _PyIndi.IBLOB_format_set)
    blob = property(_PyIndi.IBLOB_blob_get, _PyIndi.IBLOB_blob_set)
    bloblen = property(_PyIndi.IBLOB_bloblen_get, _PyIndi.IBLOB_bloblen_set)
    size = property(_PyIndi.IBLOB_size_get, _PyIndi.IBLOB_size_set)
    bvp = property(_PyIndi.IBLOB_bvp_get, _PyIndi.IBLOB_bvp_set)
    aux0 = property(_PyIndi.IBLOB_aux0_get, _PyIndi.IBLOB_aux0_set)
    aux1 = property(_PyIndi.IBLOB_aux1_get, _PyIndi.IBLOB_aux1_set)
    aux2 = property(_PyIndi.IBLOB_aux2_get, _PyIndi.IBLOB_aux2_set)

    def getblobdata(self):
        return _PyIndi.IBLOB_getblobdata(self)

    def __init__(self):
        _PyIndi.IBLOB_swiginit(self, _PyIndi.new_IBLOB())
    __swig_destroy__ = _PyIndi.delete_IBLOB

# Register IBLOB in _PyIndi:
_PyIndi.IBLOB_swigregister(IBLOB)
class IBLOBVectorProperty(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    device = property(_PyIndi.IBLOBVectorProperty_device_get, _PyIndi.IBLOBVectorProperty_device_set)
    name = property(_PyIndi.IBLOBVectorProperty_name_get, _PyIndi.IBLOBVectorProperty_name_set)
    label = property(_PyIndi.IBLOBVectorProperty_label_get, _PyIndi.IBLOBVectorProperty_label_set)
    group = property(_PyIndi.IBLOBVectorProperty_group_get, _PyIndi.IBLOBVectorProperty_group_set)
    p = property(_PyIndi.IBLOBVectorProperty_p_get, _PyIndi.IBLOBVectorProperty_p_set)
    timeout = property(_PyIndi.IBLOBVectorProperty_timeout_get, _PyIndi.IBLOBVectorProperty_timeout_set)
    s = property(_PyIndi.IBLOBVectorProperty_s_get, _PyIndi.IBLOBVectorProperty_s_set)
    bp = property(_PyIndi.IBLOBVectorProperty_bp_get, _PyIndi.IBLOBVectorProperty_bp_set)
    nbp = property(_PyIndi.IBLOBVectorProperty_nbp_get, _PyIndi.IBLOBVectorProperty_nbp_set)
    timestamp = property(_PyIndi.IBLOBVectorProperty_timestamp_get, _PyIndi.IBLOBVectorProperty_timestamp_set)
    aux = property(_PyIndi.IBLOBVectorProperty_aux_get, _PyIndi.IBLOBVectorProperty_aux_set)

    def __getitem__(self, index):
        return _PyIndi.IBLOBVectorProperty___getitem__(self, index)

    def __len__(self):
        return _PyIndi.IBLOBVectorProperty___len__(self)

    def __init__(self):
        _PyIndi.IBLOBVectorProperty_swiginit(self, _PyIndi.new_IBLOBVectorProperty())
    __swig_destroy__ = _PyIndi.delete_IBLOBVectorProperty

# Register IBLOBVectorProperty in _PyIndi:
_PyIndi.IBLOBVectorProperty_swigregister(IBLOBVectorProperty)
MAXRBUF = _PyIndi.MAXRBUF
class BaseMediator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _PyIndi.delete_BaseMediator

    def updateProperty(self, property):
        return _PyIndi.BaseMediator_updateProperty(self, property)

    def serverConnected(self):
        return _PyIndi.BaseMediator_serverConnected(self)

    def serverDisconnected(self, exit_code):
        return _PyIndi.BaseMediator_serverDisconnected(self, exit_code)

    def newDevice(self, *args):
        return _PyIndi.BaseMediator_newDevice(self, *args)

    def removeDevice(self, *args):
        return _PyIndi.BaseMediator_removeDevice(self, *args)

    def newProperty(self, *args):
        return _PyIndi.BaseMediator_newProperty(self, *args)

    def removeProperty(self, *args):
        return _PyIndi.BaseMediator_removeProperty(self, *args)

    def newSwitch(self, svp):
        return _PyIndi.BaseMediator_newSwitch(self, svp)

    def newNumber(self, nvp):
        return _PyIndi.BaseMediator_newNumber(self, nvp)

    def newText(self, tvp):
        return _PyIndi.BaseMediator_newText(self, tvp)

    def newLight(self, lvp):
        return _PyIndi.BaseMediator_newLight(self, lvp)

    def newBLOB(self, bp):
        return _PyIndi.BaseMediator_newBLOB(self, bp)

    def newMessage(self, *args):
        return _PyIndi.BaseMediator_newMessage(self, *args)

    def __init__(self):
        if self.__class__ == BaseMediator:
            _self = None
        else:
            _self = self
        _PyIndi.BaseMediator_swiginit(self, _PyIndi.new_BaseMediator(_self, ))
    def __disown__(self):
        self.this.disown()
        _PyIndi.disown_BaseMediator(self)
        return weakref.proxy(self)

# Register BaseMediator in _PyIndi:
_PyIndi.BaseMediator_swigregister(BaseMediator)
class AbstractBaseClient(BaseMediator):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _PyIndi.delete_AbstractBaseClient

    def setServer(self, hostname, port):
        return _PyIndi.AbstractBaseClient_setServer(self, hostname, port)

    def getHost(self):
        return _PyIndi.AbstractBaseClient_getHost(self)

    def getPort(self):
        return _PyIndi.AbstractBaseClient_getPort(self)

    def connectServer(self):
        return _PyIndi.AbstractBaseClient_connectServer(self)

    def disconnectServer(self, exit_code=0):
        return _PyIndi.AbstractBaseClient_disconnectServer(self, exit_code)

    def isServerConnected(self):
        return _PyIndi.AbstractBaseClient_isServerConnected(self)

    def setConnectionTimeout(self, seconds, microseconds):
        return _PyIndi.AbstractBaseClient_setConnectionTimeout(self, seconds, microseconds)

    def setVerbose(self, enable):
        return _PyIndi.AbstractBaseClient_setVerbose(self, enable)

    def isVerbose(self):
        return _PyIndi.AbstractBaseClient_isVerbose(self)

    def watchDevice(self, *args):
        return _PyIndi.AbstractBaseClient_watchDevice(self, *args)

    def watchProperty(self, deviceName, propertyName):
        return _PyIndi.AbstractBaseClient_watchProperty(self, deviceName, propertyName)

    def connectDevice(self, deviceName):
        return _PyIndi.AbstractBaseClient_connectDevice(self, deviceName)

    def disconnectDevice(self, deviceName):
        return _PyIndi.AbstractBaseClient_disconnectDevice(self, deviceName)

    def getDevice(self, deviceName):
        return _PyIndi.AbstractBaseClient_getDevice(self, deviceName)

    def getDevices(self, *args):
        return _PyIndi.AbstractBaseClient_getDevices(self, *args)

    def setBLOBMode(self, blobH, dev, prop=None):
        return _PyIndi.AbstractBaseClient_setBLOBMode(self, blobH, dev, prop)

    def getBLOBMode(self, dev, prop=None):
        return _PyIndi.AbstractBaseClient_getBLOBMode(self, dev, prop)

    def sendNewProperty(self, pp):
        return _PyIndi.AbstractBaseClient_sendNewProperty(self, pp)

    def sendNewText(self, *args):
        return _PyIndi.AbstractBaseClient_sendNewText(self, *args)

    def sendNewNumber(self, *args):
        return _PyIndi.AbstractBaseClient_sendNewNumber(self, *args)

    def sendNewSwitch(self, *args):
        return _PyIndi.AbstractBaseClient_sendNewSwitch(self, *args)

    def startBlob(self, devName, propName, timestamp):
        return _PyIndi.AbstractBaseClient_startBlob(self, devName, propName, timestamp)

    def sendOneBlob(self, *args):
        return _PyIndi.AbstractBaseClient_sendOneBlob(self, *args)

    def finishBlob(self):
        return _PyIndi.AbstractBaseClient_finishBlob(self)

    def sendPingRequest(self, uid):
        return _PyIndi.AbstractBaseClient_sendPingRequest(self, uid)

    def sendPingReply(self, uid):
        return _PyIndi.AbstractBaseClient_sendPingReply(self, uid)

# Register AbstractBaseClient in _PyIndi:
_PyIndi.AbstractBaseClient_swigregister(AbstractBaseClient)
class BaseDeviceVectorShared(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _PyIndi.BaseDeviceVectorShared_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _PyIndi.BaseDeviceVectorShared___nonzero__(self)

    def __bool__(self):
        return _PyIndi.BaseDeviceVectorShared___bool__(self)

    def __len__(self):
        return _PyIndi.BaseDeviceVectorShared___len__(self)

    def __getslice__(self, i, j):
        return _PyIndi.BaseDeviceVectorShared___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _PyIndi.BaseDeviceVectorShared___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _PyIndi.BaseDeviceVectorShared___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _PyIndi.BaseDeviceVectorShared___delitem__(self, *args)

    def __getitem__(self, *args):
        return _PyIndi.BaseDeviceVectorShared___getitem__(self, *args)

    def __setitem__(self, *args):
        return _PyIndi.BaseDeviceVectorShared___setitem__(self, *args)

    def pop(self):
        return _PyIndi.BaseDeviceVectorShared_pop(self)

    def append(self, x):
        return _PyIndi.BaseDeviceVectorShared_append(self, x)

    def empty(self):
        return _PyIndi.BaseDeviceVectorShared_empty(self)

    def size(self):
        return _PyIndi.BaseDeviceVectorShared_size(self)

    def swap(self, v):
        return _PyIndi.BaseDeviceVectorShared_swap(self, v)

    def begin(self):
        return _PyIndi.BaseDeviceVectorShared_begin(self)

    def end(self):
        return _PyIndi.BaseDeviceVectorShared_end(self)

    def rbegin(self):
        return _PyIndi.BaseDeviceVectorShared_rbegin(self)

    def rend(self):
        return _PyIndi.BaseDeviceVectorShared_rend(self)

    def clear(self):
        return _PyIndi.BaseDeviceVectorShared_clear(self)

    def get_allocator(self):
        return _PyIndi.BaseDeviceVectorShared_get_allocator(self)

    def pop_back(self):
        return _PyIndi.BaseDeviceVectorShared_pop_back(self)

    def erase(self, *args):
        return _PyIndi.BaseDeviceVectorShared_erase(self, *args)

    def __init__(self, *args):
        _PyIndi.BaseDeviceVectorShared_swiginit(self, _PyIndi.new_BaseDeviceVectorShared(*args))

    def push_back(self, x):
        return _PyIndi.BaseDeviceVectorShared_push_back(self, x)

    def front(self):
        return _PyIndi.BaseDeviceVectorShared_front(self)

    def back(self):
        return _PyIndi.BaseDeviceVectorShared_back(self)

    def assign(self, n, x):
        return _PyIndi.BaseDeviceVectorShared_assign(self, n, x)

    def resize(self, *args):
        return _PyIndi.BaseDeviceVectorShared_resize(self, *args)

    def insert(self, *args):
        return _PyIndi.BaseDeviceVectorShared_insert(self, *args)

    def reserve(self, n):
        return _PyIndi.BaseDeviceVectorShared_reserve(self, n)

    def capacity(self):
        return _PyIndi.BaseDeviceVectorShared_capacity(self)
    __swig_destroy__ = _PyIndi.delete_BaseDeviceVectorShared

# Register BaseDeviceVectorShared in _PyIndi:
_PyIndi.BaseDeviceVectorShared_swigregister(BaseDeviceVectorShared)
class BaseClient(AbstractBaseClient):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        if self.__class__ == BaseClient:
            _self = None
        else:
            _self = self
        _PyIndi.BaseClient_swiginit(self, _PyIndi.new_BaseClient(_self, ))
    __swig_destroy__ = _PyIndi.delete_BaseClient

    def connectServer(self):
        return _PyIndi.BaseClient_connectServer(self)

    def disconnectServer(self, exit_code=0):
        return _PyIndi.BaseClient_disconnectServer(self, exit_code)

    def enableDirectBlobAccess(self, dev=None, prop=None):
        return _PyIndi.BaseClient_enableDirectBlobAccess(self, dev, prop)

    def sendOneBlobFromBuffer(self, name, type, data):
        return _PyIndi.BaseClient_sendOneBlobFromBuffer(self, name, type, data)
    def __disown__(self):
        self.this.disown()
        _PyIndi.disown_BaseClient(self)
        return weakref.proxy(self)

    def newPingReply(self, uid):
        return _PyIndi.BaseClient_newPingReply(self, uid)

    def newUniversalMessage(self, message):
        return _PyIndi.BaseClient_newUniversalMessage(self, message)

# Register BaseClient in _PyIndi:
_PyIndi.BaseClient_swigregister(BaseClient)
class BaseDevice(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    INDI_DEVICE_NOT_FOUND = _PyIndi.BaseDevice_INDI_DEVICE_NOT_FOUND
    INDI_PROPERTY_INVALID = _PyIndi.BaseDevice_INDI_PROPERTY_INVALID
    INDI_PROPERTY_DUPLICATED = _PyIndi.BaseDevice_INDI_PROPERTY_DUPLICATED
    INDI_DISPATCH_ERROR = _PyIndi.BaseDevice_INDI_DISPATCH_ERROR
    INDI_ENABLED = _PyIndi.BaseDevice_INDI_ENABLED
    INDI_DISABLED = _PyIndi.BaseDevice_INDI_DISABLED
    GENERAL_INTERFACE = _PyIndi.BaseDevice_GENERAL_INTERFACE
    TELESCOPE_INTERFACE = _PyIndi.BaseDevice_TELESCOPE_INTERFACE
    CCD_INTERFACE = _PyIndi.BaseDevice_CCD_INTERFACE
    GUIDER_INTERFACE = _PyIndi.BaseDevice_GUIDER_INTERFACE
    FOCUSER_INTERFACE = _PyIndi.BaseDevice_FOCUSER_INTERFACE
    FILTER_INTERFACE = _PyIndi.BaseDevice_FILTER_INTERFACE
    DOME_INTERFACE = _PyIndi.BaseDevice_DOME_INTERFACE
    GPS_INTERFACE = _PyIndi.BaseDevice_GPS_INTERFACE
    WEATHER_INTERFACE = _PyIndi.BaseDevice_WEATHER_INTERFACE
    AO_INTERFACE = _PyIndi.BaseDevice_AO_INTERFACE
    DUSTCAP_INTERFACE = _PyIndi.BaseDevice_DUSTCAP_INTERFACE
    LIGHTBOX_INTERFACE = _PyIndi.BaseDevice_LIGHTBOX_INTERFACE
    DETECTOR_INTERFACE = _PyIndi.BaseDevice_DETECTOR_INTERFACE
    ROTATOR_INTERFACE = _PyIndi.BaseDevice_ROTATOR_INTERFACE
    SPECTROGRAPH_INTERFACE = _PyIndi.BaseDevice_SPECTROGRAPH_INTERFACE
    CORRELATOR_INTERFACE = _PyIndi.BaseDevice_CORRELATOR_INTERFACE
    AUX_INTERFACE = _PyIndi.BaseDevice_AUX_INTERFACE
    SENSOR_INTERFACE = _PyIndi.BaseDevice_SENSOR_INTERFACE

    def __init__(self):
        _PyIndi.BaseDevice_swiginit(self, _PyIndi.new_BaseDevice())
    __swig_destroy__ = _PyIndi.delete_BaseDevice

    def registerProperty(self, *args):
        return _PyIndi.BaseDevice_registerProperty(self, *args)

    def removeProperty(self, name, errmsg):
        return _PyIndi.BaseDevice_removeProperty(self, name, errmsg)

    def watchProperty(self, name, callback):
        return _PyIndi.BaseDevice_watchProperty(self, name, callback)

    def getProperty(self, name, type=INDI_UNKNOWN):
        return _PyIndi.BaseDevice_getProperty(self, name, type)

    def getProperties(self, *args):
        return _PyIndi.BaseDevice_getProperties(self, *args)

    def getNumber(self, name):
        return _PyIndi.BaseDevice_getNumber(self, name)

    def getText(self, name):
        return _PyIndi.BaseDevice_getText(self, name)

    def getSwitch(self, name):
        return _PyIndi.BaseDevice_getSwitch(self, name)

    def getLight(self, name):
        return _PyIndi.BaseDevice_getLight(self, name)

    def getBLOB(self, name):
        return _PyIndi.BaseDevice_getBLOB(self, name)

    def getPropertyState(self, name):
        return _PyIndi.BaseDevice_getPropertyState(self, name)

    def getPropertyPermission(self, name):
        return _PyIndi.BaseDevice_getPropertyPermission(self, name)

    def getRawProperty(self, name, type=INDI_UNKNOWN):
        return _PyIndi.BaseDevice_getRawProperty(self, name, type)

    def addMessage(self, msg):
        return _PyIndi.BaseDevice_addMessage(self, msg)

    def checkMessage(self, root):
        return _PyIndi.BaseDevice_checkMessage(self, root)

    def doMessage(self, msg):
        return _PyIndi.BaseDevice_doMessage(self, msg)

    def messageQueue(self, index):
        return _PyIndi.BaseDevice_messageQueue(self, index)

    def lastMessage(self):
        return _PyIndi.BaseDevice_lastMessage(self)

    def isValid(self):
        return _PyIndi.BaseDevice_isValid(self)

    def isConnected(self):
        return _PyIndi.BaseDevice_isConnected(self)

    def attach(self):
        return _PyIndi.BaseDevice_attach(self)

    def detach(self):
        return _PyIndi.BaseDevice_detach(self)

    def setMediator(self, mediator):
        return _PyIndi.BaseDevice_setMediator(self, mediator)

    def getMediator(self):
        return _PyIndi.BaseDevice_getMediator(self)

    def setDeviceName(self, dev):
        return _PyIndi.BaseDevice_setDeviceName(self, dev)

    def getDeviceName(self):
        return _PyIndi.BaseDevice_getDeviceName(self)

    def isDeviceNameMatch(self, *args):
        return _PyIndi.BaseDevice_isDeviceNameMatch(self, *args)

    def getDriverName(self):
        return _PyIndi.BaseDevice_getDriverName(self)

    def getDriverExec(self):
        return _PyIndi.BaseDevice_getDriverExec(self)

    def getDriverVersion(self):
        return _PyIndi.BaseDevice_getDriverVersion(self)

    def getDriverInterface(self):
        return _PyIndi.BaseDevice_getDriverInterface(self)

    def buildSkeleton(self, filename):
        return _PyIndi.BaseDevice_buildSkeleton(self, filename)

    def buildProp(self, root, errmsg, isDynamic=False):
        return _PyIndi.BaseDevice_buildProp(self, root, errmsg, isDynamic)

    def setValue(self, root, errmsg):
        return _PyIndi.BaseDevice_setValue(self, root, errmsg)

    def __deref__(self):
        return _PyIndi.BaseDevice___deref__(self)

    def __ne__(self, arg2):
        return _PyIndi.BaseDevice___ne__(self, arg2)

    def __eq__(self, arg2):
        return _PyIndi.BaseDevice___eq__(self, arg2)

    def __nonzero__(self):
        return _PyIndi.BaseDevice___nonzero__(self)
    __bool__ = __nonzero__



# Register BaseDevice in _PyIndi:
_PyIndi.BaseDevice_swigregister(BaseDevice)
class PropertyViewText(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _PyIndi.PropertyViewText_swiginit(self, _PyIndi.new_PropertyViewText())

    def setDeviceName(self, *args):
        return _PyIndi.PropertyViewText_setDeviceName(self, *args)

    def setName(self, *args):
        return _PyIndi.PropertyViewText_setName(self, *args)

    def setLabel(self, *args):
        return _PyIndi.PropertyViewText_setLabel(self, *args)

    def setGroupName(self, *args):
        return _PyIndi.PropertyViewText_setGroupName(self, *args)

    def setPermission(self, permission):
        return _PyIndi.PropertyViewText_setPermission(self, permission)

    def setTimeout(self, timeout):
        return _PyIndi.PropertyViewText_setTimeout(self, timeout)

    def setState(self, state):
        return _PyIndi.PropertyViewText_setState(self, state)

    def setTimestamp(self, *args):
        return _PyIndi.PropertyViewText_setTimestamp(self, *args)

    def setAux(self, user):
        return _PyIndi.PropertyViewText_setAux(self, user)

    def setWidgets(self, w, count):
        return _PyIndi.PropertyViewText_setWidgets(self, w, count)

    def setRule(self, *args):
        return _PyIndi.PropertyViewText_setRule(self, *args)

    def getDeviceName(self):
        return _PyIndi.PropertyViewText_getDeviceName(self)

    def getName(self):
        return _PyIndi.PropertyViewText_getName(self)

    def getLabel(self):
        return _PyIndi.PropertyViewText_getLabel(self)

    def getGroupName(self):
        return _PyIndi.PropertyViewText_getGroupName(self)

    def getPermission(self):
        return _PyIndi.PropertyViewText_getPermission(self)

    def getPermissionAsString(self):
        return _PyIndi.PropertyViewText_getPermissionAsString(self)

    def getRule(self):
        return _PyIndi.PropertyViewText_getRule(self)

    def getRuleAsString(self):
        return _PyIndi.PropertyViewText_getRuleAsString(self)

    def getTimeout(self):
        return _PyIndi.PropertyViewText_getTimeout(self)

    def getState(self):
        return _PyIndi.PropertyViewText_getState(self)

    def getStateAsString(self):
        return _PyIndi.PropertyViewText_getStateAsString(self)

    def getTimestamp(self):
        return _PyIndi.PropertyViewText_getTimestamp(self)

    def getAux(self):
        return _PyIndi.PropertyViewText_getAux(self)

    def count(self):
        return _PyIndi.PropertyViewText_count(self)

    def widget(self):
        return _PyIndi.PropertyViewText_widget(self)

    def findWidgetByName(self, name):
        return _PyIndi.PropertyViewText_findWidgetByName(self, name)

    def isEmpty(self):
        return _PyIndi.PropertyViewText_isEmpty(self)

    def isNameMatch(self, *args):
        return _PyIndi.PropertyViewText_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.PropertyViewText_isLabelMatch(self, *args)

    def save(self, f):
        return _PyIndi.PropertyViewText_save(self, f)

    def begin(self):
        return _PyIndi.PropertyViewText_begin(self)

    def end(self):
        return _PyIndi.PropertyViewText_end(self)

    def at(self, index):
        return _PyIndi.PropertyViewText_at(self, index)

    def clear(self):
        return _PyIndi.PropertyViewText_clear(self)

    def __getitem__(self, index):
        return _PyIndi.PropertyViewText___getitem__(self, index)

    def __len__(self):
        return _PyIndi.PropertyViewText___len__(self)
    __swig_destroy__ = _PyIndi.delete_PropertyViewText

# Register PropertyViewText in _PyIndi:
_PyIndi.PropertyViewText_swigregister(PropertyViewText)
class PropertyViewNumber(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _PyIndi.PropertyViewNumber_swiginit(self, _PyIndi.new_PropertyViewNumber())

    def setDeviceName(self, *args):
        return _PyIndi.PropertyViewNumber_setDeviceName(self, *args)

    def setName(self, *args):
        return _PyIndi.PropertyViewNumber_setName(self, *args)

    def setLabel(self, *args):
        return _PyIndi.PropertyViewNumber_setLabel(self, *args)

    def setGroupName(self, *args):
        return _PyIndi.PropertyViewNumber_setGroupName(self, *args)

    def setPermission(self, permission):
        return _PyIndi.PropertyViewNumber_setPermission(self, permission)

    def setTimeout(self, timeout):
        return _PyIndi.PropertyViewNumber_setTimeout(self, timeout)

    def setState(self, state):
        return _PyIndi.PropertyViewNumber_setState(self, state)

    def setTimestamp(self, *args):
        return _PyIndi.PropertyViewNumber_setTimestamp(self, *args)

    def setAux(self, user):
        return _PyIndi.PropertyViewNumber_setAux(self, user)

    def setWidgets(self, w, count):
        return _PyIndi.PropertyViewNumber_setWidgets(self, w, count)

    def setRule(self, *args):
        return _PyIndi.PropertyViewNumber_setRule(self, *args)

    def getDeviceName(self):
        return _PyIndi.PropertyViewNumber_getDeviceName(self)

    def getName(self):
        return _PyIndi.PropertyViewNumber_getName(self)

    def getLabel(self):
        return _PyIndi.PropertyViewNumber_getLabel(self)

    def getGroupName(self):
        return _PyIndi.PropertyViewNumber_getGroupName(self)

    def getPermission(self):
        return _PyIndi.PropertyViewNumber_getPermission(self)

    def getPermissionAsString(self):
        return _PyIndi.PropertyViewNumber_getPermissionAsString(self)

    def getRule(self):
        return _PyIndi.PropertyViewNumber_getRule(self)

    def getRuleAsString(self):
        return _PyIndi.PropertyViewNumber_getRuleAsString(self)

    def getTimeout(self):
        return _PyIndi.PropertyViewNumber_getTimeout(self)

    def getState(self):
        return _PyIndi.PropertyViewNumber_getState(self)

    def getStateAsString(self):
        return _PyIndi.PropertyViewNumber_getStateAsString(self)

    def getTimestamp(self):
        return _PyIndi.PropertyViewNumber_getTimestamp(self)

    def getAux(self):
        return _PyIndi.PropertyViewNumber_getAux(self)

    def count(self):
        return _PyIndi.PropertyViewNumber_count(self)

    def widget(self):
        return _PyIndi.PropertyViewNumber_widget(self)

    def findWidgetByName(self, name):
        return _PyIndi.PropertyViewNumber_findWidgetByName(self, name)

    def isEmpty(self):
        return _PyIndi.PropertyViewNumber_isEmpty(self)

    def isNameMatch(self, *args):
        return _PyIndi.PropertyViewNumber_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.PropertyViewNumber_isLabelMatch(self, *args)

    def save(self, f):
        return _PyIndi.PropertyViewNumber_save(self, f)

    def begin(self):
        return _PyIndi.PropertyViewNumber_begin(self)

    def end(self):
        return _PyIndi.PropertyViewNumber_end(self)

    def at(self, index):
        return _PyIndi.PropertyViewNumber_at(self, index)

    def clear(self):
        return _PyIndi.PropertyViewNumber_clear(self)

    def __getitem__(self, index):
        return _PyIndi.PropertyViewNumber___getitem__(self, index)

    def __len__(self):
        return _PyIndi.PropertyViewNumber___len__(self)
    __swig_destroy__ = _PyIndi.delete_PropertyViewNumber

# Register PropertyViewNumber in _PyIndi:
_PyIndi.PropertyViewNumber_swigregister(PropertyViewNumber)
class PropertyViewSwitch(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _PyIndi.PropertyViewSwitch_swiginit(self, _PyIndi.new_PropertyViewSwitch())

    def setDeviceName(self, *args):
        return _PyIndi.PropertyViewSwitch_setDeviceName(self, *args)

    def setName(self, *args):
        return _PyIndi.PropertyViewSwitch_setName(self, *args)

    def setLabel(self, *args):
        return _PyIndi.PropertyViewSwitch_setLabel(self, *args)

    def setGroupName(self, *args):
        return _PyIndi.PropertyViewSwitch_setGroupName(self, *args)

    def setPermission(self, permission):
        return _PyIndi.PropertyViewSwitch_setPermission(self, permission)

    def setTimeout(self, timeout):
        return _PyIndi.PropertyViewSwitch_setTimeout(self, timeout)

    def setState(self, state):
        return _PyIndi.PropertyViewSwitch_setState(self, state)

    def setTimestamp(self, *args):
        return _PyIndi.PropertyViewSwitch_setTimestamp(self, *args)

    def setAux(self, user):
        return _PyIndi.PropertyViewSwitch_setAux(self, user)

    def setWidgets(self, w, count):
        return _PyIndi.PropertyViewSwitch_setWidgets(self, w, count)

    def setRule(self, *args):
        return _PyIndi.PropertyViewSwitch_setRule(self, *args)

    def getDeviceName(self):
        return _PyIndi.PropertyViewSwitch_getDeviceName(self)

    def getName(self):
        return _PyIndi.PropertyViewSwitch_getName(self)

    def getLabel(self):
        return _PyIndi.PropertyViewSwitch_getLabel(self)

    def getGroupName(self):
        return _PyIndi.PropertyViewSwitch_getGroupName(self)

    def getPermission(self):
        return _PyIndi.PropertyViewSwitch_getPermission(self)

    def getPermissionAsString(self):
        return _PyIndi.PropertyViewSwitch_getPermissionAsString(self)

    def getRule(self):
        return _PyIndi.PropertyViewSwitch_getRule(self)

    def getRuleAsString(self):
        return _PyIndi.PropertyViewSwitch_getRuleAsString(self)

    def getTimeout(self):
        return _PyIndi.PropertyViewSwitch_getTimeout(self)

    def getState(self):
        return _PyIndi.PropertyViewSwitch_getState(self)

    def getStateAsString(self):
        return _PyIndi.PropertyViewSwitch_getStateAsString(self)

    def getTimestamp(self):
        return _PyIndi.PropertyViewSwitch_getTimestamp(self)

    def getAux(self):
        return _PyIndi.PropertyViewSwitch_getAux(self)

    def count(self):
        return _PyIndi.PropertyViewSwitch_count(self)

    def widget(self):
        return _PyIndi.PropertyViewSwitch_widget(self)

    def findWidgetByName(self, name):
        return _PyIndi.PropertyViewSwitch_findWidgetByName(self, name)

    def isEmpty(self):
        return _PyIndi.PropertyViewSwitch_isEmpty(self)

    def isNameMatch(self, *args):
        return _PyIndi.PropertyViewSwitch_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.PropertyViewSwitch_isLabelMatch(self, *args)

    def save(self, f):
        return _PyIndi.PropertyViewSwitch_save(self, f)

    def begin(self):
        return _PyIndi.PropertyViewSwitch_begin(self)

    def end(self):
        return _PyIndi.PropertyViewSwitch_end(self)

    def at(self, index):
        return _PyIndi.PropertyViewSwitch_at(self, index)

    def clear(self):
        return _PyIndi.PropertyViewSwitch_clear(self)

    def __getitem__(self, index):
        return _PyIndi.PropertyViewSwitch___getitem__(self, index)

    def __len__(self):
        return _PyIndi.PropertyViewSwitch___len__(self)
    __swig_destroy__ = _PyIndi.delete_PropertyViewSwitch

# Register PropertyViewSwitch in _PyIndi:
_PyIndi.PropertyViewSwitch_swigregister(PropertyViewSwitch)
class PropertyViewLight(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _PyIndi.PropertyViewLight_swiginit(self, _PyIndi.new_PropertyViewLight())

    def setDeviceName(self, *args):
        return _PyIndi.PropertyViewLight_setDeviceName(self, *args)

    def setName(self, *args):
        return _PyIndi.PropertyViewLight_setName(self, *args)

    def setLabel(self, *args):
        return _PyIndi.PropertyViewLight_setLabel(self, *args)

    def setGroupName(self, *args):
        return _PyIndi.PropertyViewLight_setGroupName(self, *args)

    def setPermission(self, permission):
        return _PyIndi.PropertyViewLight_setPermission(self, permission)

    def setTimeout(self, timeout):
        return _PyIndi.PropertyViewLight_setTimeout(self, timeout)

    def setState(self, state):
        return _PyIndi.PropertyViewLight_setState(self, state)

    def setTimestamp(self, *args):
        return _PyIndi.PropertyViewLight_setTimestamp(self, *args)

    def setAux(self, user):
        return _PyIndi.PropertyViewLight_setAux(self, user)

    def setWidgets(self, w, count):
        return _PyIndi.PropertyViewLight_setWidgets(self, w, count)

    def setRule(self, *args):
        return _PyIndi.PropertyViewLight_setRule(self, *args)

    def getDeviceName(self):
        return _PyIndi.PropertyViewLight_getDeviceName(self)

    def getName(self):
        return _PyIndi.PropertyViewLight_getName(self)

    def getLabel(self):
        return _PyIndi.PropertyViewLight_getLabel(self)

    def getGroupName(self):
        return _PyIndi.PropertyViewLight_getGroupName(self)

    def getPermission(self):
        return _PyIndi.PropertyViewLight_getPermission(self)

    def getPermissionAsString(self):
        return _PyIndi.PropertyViewLight_getPermissionAsString(self)

    def getRule(self):
        return _PyIndi.PropertyViewLight_getRule(self)

    def getRuleAsString(self):
        return _PyIndi.PropertyViewLight_getRuleAsString(self)

    def getTimeout(self):
        return _PyIndi.PropertyViewLight_getTimeout(self)

    def getState(self):
        return _PyIndi.PropertyViewLight_getState(self)

    def getStateAsString(self):
        return _PyIndi.PropertyViewLight_getStateAsString(self)

    def getTimestamp(self):
        return _PyIndi.PropertyViewLight_getTimestamp(self)

    def getAux(self):
        return _PyIndi.PropertyViewLight_getAux(self)

    def count(self):
        return _PyIndi.PropertyViewLight_count(self)

    def widget(self):
        return _PyIndi.PropertyViewLight_widget(self)

    def findWidgetByName(self, name):
        return _PyIndi.PropertyViewLight_findWidgetByName(self, name)

    def isEmpty(self):
        return _PyIndi.PropertyViewLight_isEmpty(self)

    def isNameMatch(self, *args):
        return _PyIndi.PropertyViewLight_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.PropertyViewLight_isLabelMatch(self, *args)

    def save(self, f):
        return _PyIndi.PropertyViewLight_save(self, f)

    def begin(self):
        return _PyIndi.PropertyViewLight_begin(self)

    def end(self):
        return _PyIndi.PropertyViewLight_end(self)

    def at(self, index):
        return _PyIndi.PropertyViewLight_at(self, index)

    def clear(self):
        return _PyIndi.PropertyViewLight_clear(self)

    def __getitem__(self, index):
        return _PyIndi.PropertyViewLight___getitem__(self, index)

    def __len__(self):
        return _PyIndi.PropertyViewLight___len__(self)
    __swig_destroy__ = _PyIndi.delete_PropertyViewLight

# Register PropertyViewLight in _PyIndi:
_PyIndi.PropertyViewLight_swigregister(PropertyViewLight)
class PropertyViewBlob(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _PyIndi.PropertyViewBlob_swiginit(self, _PyIndi.new_PropertyViewBlob())

    def setDeviceName(self, *args):
        return _PyIndi.PropertyViewBlob_setDeviceName(self, *args)

    def setName(self, *args):
        return _PyIndi.PropertyViewBlob_setName(self, *args)

    def setLabel(self, *args):
        return _PyIndi.PropertyViewBlob_setLabel(self, *args)

    def setGroupName(self, *args):
        return _PyIndi.PropertyViewBlob_setGroupName(self, *args)

    def setPermission(self, permission):
        return _PyIndi.PropertyViewBlob_setPermission(self, permission)

    def setTimeout(self, timeout):
        return _PyIndi.PropertyViewBlob_setTimeout(self, timeout)

    def setState(self, state):
        return _PyIndi.PropertyViewBlob_setState(self, state)

    def setTimestamp(self, *args):
        return _PyIndi.PropertyViewBlob_setTimestamp(self, *args)

    def setAux(self, user):
        return _PyIndi.PropertyViewBlob_setAux(self, user)

    def setWidgets(self, w, count):
        return _PyIndi.PropertyViewBlob_setWidgets(self, w, count)

    def setRule(self, *args):
        return _PyIndi.PropertyViewBlob_setRule(self, *args)

    def getDeviceName(self):
        return _PyIndi.PropertyViewBlob_getDeviceName(self)

    def getName(self):
        return _PyIndi.PropertyViewBlob_getName(self)

    def getLabel(self):
        return _PyIndi.PropertyViewBlob_getLabel(self)

    def getGroupName(self):
        return _PyIndi.PropertyViewBlob_getGroupName(self)

    def getPermission(self):
        return _PyIndi.PropertyViewBlob_getPermission(self)

    def getPermissionAsString(self):
        return _PyIndi.PropertyViewBlob_getPermissionAsString(self)

    def getRule(self):
        return _PyIndi.PropertyViewBlob_getRule(self)

    def getRuleAsString(self):
        return _PyIndi.PropertyViewBlob_getRuleAsString(self)

    def getTimeout(self):
        return _PyIndi.PropertyViewBlob_getTimeout(self)

    def getState(self):
        return _PyIndi.PropertyViewBlob_getState(self)

    def getStateAsString(self):
        return _PyIndi.PropertyViewBlob_getStateAsString(self)

    def getTimestamp(self):
        return _PyIndi.PropertyViewBlob_getTimestamp(self)

    def getAux(self):
        return _PyIndi.PropertyViewBlob_getAux(self)

    def count(self):
        return _PyIndi.PropertyViewBlob_count(self)

    def widget(self):
        return _PyIndi.PropertyViewBlob_widget(self)

    def findWidgetByName(self, name):
        return _PyIndi.PropertyViewBlob_findWidgetByName(self, name)

    def isEmpty(self):
        return _PyIndi.PropertyViewBlob_isEmpty(self)

    def isNameMatch(self, *args):
        return _PyIndi.PropertyViewBlob_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.PropertyViewBlob_isLabelMatch(self, *args)

    def save(self, f):
        return _PyIndi.PropertyViewBlob_save(self, f)

    def begin(self):
        return _PyIndi.PropertyViewBlob_begin(self)

    def end(self):
        return _PyIndi.PropertyViewBlob_end(self)

    def at(self, index):
        return _PyIndi.PropertyViewBlob_at(self, index)

    def clear(self):
        return _PyIndi.PropertyViewBlob_clear(self)

    def __getitem__(self, index):
        return _PyIndi.PropertyViewBlob___getitem__(self, index)

    def __len__(self):
        return _PyIndi.PropertyViewBlob___len__(self)
    __swig_destroy__ = _PyIndi.delete_PropertyViewBlob

# Register PropertyViewBlob in _PyIndi:
_PyIndi.PropertyViewBlob_swigregister(PropertyViewBlob)
class WidgetViewText(IText):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _PyIndi.WidgetViewText_swiginit(self, _PyIndi.new_WidgetViewText(*args))
    __swig_destroy__ = _PyIndi.delete_WidgetViewText

    def clear(self):
        return _PyIndi.WidgetViewText_clear(self)

    def setParent(self, *args):
        return _PyIndi.WidgetViewText_setParent(self, *args)

    def setName(self, *args):
        return _PyIndi.WidgetViewText_setName(self, *args)

    def setLabel(self, *args):
        return _PyIndi.WidgetViewText_setLabel(self, *args)

    def setText(self, *args):
        return _PyIndi.WidgetViewText_setText(self, *args)

    def setAux(self, user):
        return _PyIndi.WidgetViewText_setAux(self, user)

    def getName(self):
        return _PyIndi.WidgetViewText_getName(self)

    def getLabel(self):
        return _PyIndi.WidgetViewText_getLabel(self)

    def getText(self):
        return _PyIndi.WidgetViewText_getText(self)

    def getAux(self):
        return _PyIndi.WidgetViewText_getAux(self)

    def isNameMatch(self, *args):
        return _PyIndi.WidgetViewText_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.WidgetViewText_isLabelMatch(self, *args)

    def fill(self, *args):
        return _PyIndi.WidgetViewText_fill(self, *args)

# Register WidgetViewText in _PyIndi:
_PyIndi.WidgetViewText_swigregister(WidgetViewText)
class WidgetViewNumber(INumber):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _PyIndi.WidgetViewNumber_swiginit(self, _PyIndi.new_WidgetViewNumber(*args))
    __swig_destroy__ = _PyIndi.delete_WidgetViewNumber

    def clear(self):
        return _PyIndi.WidgetViewNumber_clear(self)

    def setParent(self, *args):
        return _PyIndi.WidgetViewNumber_setParent(self, *args)

    def setName(self, *args):
        return _PyIndi.WidgetViewNumber_setName(self, *args)

    def setLabel(self, *args):
        return _PyIndi.WidgetViewNumber_setLabel(self, *args)

    def setFormat(self, *args):
        return _PyIndi.WidgetViewNumber_setFormat(self, *args)

    def setMin(self, min):
        return _PyIndi.WidgetViewNumber_setMin(self, min)

    def setMax(self, max):
        return _PyIndi.WidgetViewNumber_setMax(self, max)

    def setMinMax(self, min, max):
        return _PyIndi.WidgetViewNumber_setMinMax(self, min, max)

    def setStep(self, step):
        return _PyIndi.WidgetViewNumber_setStep(self, step)

    def setValue(self, value):
        return _PyIndi.WidgetViewNumber_setValue(self, value)

    def setAux(self, user):
        return _PyIndi.WidgetViewNumber_setAux(self, user)

    def getName(self):
        return _PyIndi.WidgetViewNumber_getName(self)

    def getLabel(self):
        return _PyIndi.WidgetViewNumber_getLabel(self)

    def getFormat(self):
        return _PyIndi.WidgetViewNumber_getFormat(self)

    def getMin(self):
        return _PyIndi.WidgetViewNumber_getMin(self)

    def getMax(self):
        return _PyIndi.WidgetViewNumber_getMax(self)

    def getStep(self):
        return _PyIndi.WidgetViewNumber_getStep(self)

    def getValue(self):
        return _PyIndi.WidgetViewNumber_getValue(self)

    def getAux(self):
        return _PyIndi.WidgetViewNumber_getAux(self)

    def isNameMatch(self, *args):
        return _PyIndi.WidgetViewNumber_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.WidgetViewNumber_isLabelMatch(self, *args)

    def fill(self, *args):
        return _PyIndi.WidgetViewNumber_fill(self, *args)

# Register WidgetViewNumber in _PyIndi:
_PyIndi.WidgetViewNumber_swigregister(WidgetViewNumber)
class WidgetViewSwitch(ISwitch):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _PyIndi.WidgetViewSwitch_swiginit(self, _PyIndi.new_WidgetViewSwitch(*args))
    __swig_destroy__ = _PyIndi.delete_WidgetViewSwitch

    def clear(self):
        return _PyIndi.WidgetViewSwitch_clear(self)

    def setParent(self, *args):
        return _PyIndi.WidgetViewSwitch_setParent(self, *args)

    def setName(self, *args):
        return _PyIndi.WidgetViewSwitch_setName(self, *args)

    def setLabel(self, *args):
        return _PyIndi.WidgetViewSwitch_setLabel(self, *args)

    def setState(self, *args):
        return _PyIndi.WidgetViewSwitch_setState(self, *args)

    def setAux(self, user):
        return _PyIndi.WidgetViewSwitch_setAux(self, user)

    def getName(self):
        return _PyIndi.WidgetViewSwitch_getName(self)

    def getLabel(self):
        return _PyIndi.WidgetViewSwitch_getLabel(self)

    def getState(self):
        return _PyIndi.WidgetViewSwitch_getState(self)

    def getStateAsString(self):
        return _PyIndi.WidgetViewSwitch_getStateAsString(self)

    def getAux(self):
        return _PyIndi.WidgetViewSwitch_getAux(self)

    def isNameMatch(self, *args):
        return _PyIndi.WidgetViewSwitch_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.WidgetViewSwitch_isLabelMatch(self, *args)

    def fill(self, *args):
        return _PyIndi.WidgetViewSwitch_fill(self, *args)

# Register WidgetViewSwitch in _PyIndi:
_PyIndi.WidgetViewSwitch_swigregister(WidgetViewSwitch)
class WidgetViewLight(ILight):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _PyIndi.WidgetViewLight_swiginit(self, _PyIndi.new_WidgetViewLight(*args))
    __swig_destroy__ = _PyIndi.delete_WidgetViewLight

    def clear(self):
        return _PyIndi.WidgetViewLight_clear(self)

    def setParent(self, *args):
        return _PyIndi.WidgetViewLight_setParent(self, *args)

    def setName(self, *args):
        return _PyIndi.WidgetViewLight_setName(self, *args)

    def setLabel(self, *args):
        return _PyIndi.WidgetViewLight_setLabel(self, *args)

    def setState(self, *args):
        return _PyIndi.WidgetViewLight_setState(self, *args)

    def setAux(self, user):
        return _PyIndi.WidgetViewLight_setAux(self, user)

    def getName(self):
        return _PyIndi.WidgetViewLight_getName(self)

    def getLabel(self):
        return _PyIndi.WidgetViewLight_getLabel(self)

    def getState(self):
        return _PyIndi.WidgetViewLight_getState(self)

    def getStateAsString(self):
        return _PyIndi.WidgetViewLight_getStateAsString(self)

    def getAux(self):
        return _PyIndi.WidgetViewLight_getAux(self)

    def isNameMatch(self, *args):
        return _PyIndi.WidgetViewLight_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.WidgetViewLight_isLabelMatch(self, *args)

    def fill(self, *args):
        return _PyIndi.WidgetViewLight_fill(self, *args)

# Register WidgetViewLight in _PyIndi:
_PyIndi.WidgetViewLight_swigregister(WidgetViewLight)
class WidgetViewBlob(IBLOB):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _PyIndi.WidgetViewBlob_swiginit(self, _PyIndi.new_WidgetViewBlob(*args))
    __swig_destroy__ = _PyIndi.delete_WidgetViewBlob

    def clear(self):
        return _PyIndi.WidgetViewBlob_clear(self)

    def setParent(self, *args):
        return _PyIndi.WidgetViewBlob_setParent(self, *args)

    def setName(self, *args):
        return _PyIndi.WidgetViewBlob_setName(self, *args)

    def setLabel(self, *args):
        return _PyIndi.WidgetViewBlob_setLabel(self, *args)

    def setFormat(self, *args):
        return _PyIndi.WidgetViewBlob_setFormat(self, *args)

    def setBlob(self, blob):
        return _PyIndi.WidgetViewBlob_setBlob(self, blob)

    def setBlobLen(self, size):
        return _PyIndi.WidgetViewBlob_setBlobLen(self, size)

    def setSize(self, size):
        return _PyIndi.WidgetViewBlob_setSize(self, size)

    def setAux(self, user):
        return _PyIndi.WidgetViewBlob_setAux(self, user)

    def getName(self):
        return _PyIndi.WidgetViewBlob_getName(self)

    def getLabel(self):
        return _PyIndi.WidgetViewBlob_getLabel(self)

    def getFormat(self):
        return _PyIndi.WidgetViewBlob_getFormat(self)

    def getBlob(self, *args):
        return _PyIndi.WidgetViewBlob_getBlob(self, *args)

    def getBlobAsString(self):
        return _PyIndi.WidgetViewBlob_getBlobAsString(self)

    def getBlobLen(self):
        return _PyIndi.WidgetViewBlob_getBlobLen(self)

    def getSize(self):
        return _PyIndi.WidgetViewBlob_getSize(self)

    def getAux(self):
        return _PyIndi.WidgetViewBlob_getAux(self)

    def isNameMatch(self, *args):
        return _PyIndi.WidgetViewBlob_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.WidgetViewBlob_isLabelMatch(self, *args)

    def fill(self, *args):
        return _PyIndi.WidgetViewBlob_fill(self, *args)

# Register WidgetViewBlob in _PyIndi:
_PyIndi.WidgetViewBlob_swigregister(WidgetViewBlob)
class Property(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _PyIndi.delete_Property

    def __init__(self, *args):
        _PyIndi.Property_swiginit(self, _PyIndi.new_Property(*args))

    def setProperty(self, arg2):
        return _PyIndi.Property_setProperty(self, arg2)

    def setType(self, t):
        return _PyIndi.Property_setType(self, t)

    def setRegistered(self, r):
        return _PyIndi.Property_setRegistered(self, r)

    def setDynamic(self, d):
        return _PyIndi.Property_setDynamic(self, d)

    def setBaseDevice(self, *args):
        return _PyIndi.Property_setBaseDevice(self, *args)

    def getProperty(self):
        return _PyIndi.Property_getProperty(self)

    def getType(self):
        return _PyIndi.Property_getType(self)

    def getTypeAsString(self):
        return _PyIndi.Property_getTypeAsString(self)

    def getRegistered(self):
        return _PyIndi.Property_getRegistered(self)

    def isDynamic(self):
        return _PyIndi.Property_isDynamic(self)

    def getBaseDevice(self):
        return _PyIndi.Property_getBaseDevice(self)

    def setName(self, name):
        return _PyIndi.Property_setName(self, name)

    def setLabel(self, label):
        return _PyIndi.Property_setLabel(self, label)

    def setGroupName(self, groupName):
        return _PyIndi.Property_setGroupName(self, groupName)

    def setDeviceName(self, deviceName):
        return _PyIndi.Property_setDeviceName(self, deviceName)

    def setTimestamp(self, timestamp):
        return _PyIndi.Property_setTimestamp(self, timestamp)

    def setState(self, state):
        return _PyIndi.Property_setState(self, state)

    def setPermission(self, permission):
        return _PyIndi.Property_setPermission(self, permission)

    def setTimeout(self, timeout):
        return _PyIndi.Property_setTimeout(self, timeout)

    def getName(self):
        return _PyIndi.Property_getName(self)

    def getLabel(self):
        return _PyIndi.Property_getLabel(self)

    def getGroupName(self):
        return _PyIndi.Property_getGroupName(self)

    def getDeviceName(self):
        return _PyIndi.Property_getDeviceName(self)

    def getTimestamp(self):
        return _PyIndi.Property_getTimestamp(self)

    def getState(self):
        return _PyIndi.Property_getState(self)

    def getStateAsString(self):
        return _PyIndi.Property_getStateAsString(self)

    def getPermission(self):
        return _PyIndi.Property_getPermission(self)

    def isEmpty(self):
        return _PyIndi.Property_isEmpty(self)

    def isValid(self):
        return _PyIndi.Property_isValid(self)

    def isNameMatch(self, *args):
        return _PyIndi.Property_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.Property_isLabelMatch(self, *args)

    def onUpdate(self, callback):
        return _PyIndi.Property_onUpdate(self, callback)

    def emitUpdate(self):
        return _PyIndi.Property_emitUpdate(self)

    def hasUpdateCallback(self):
        return _PyIndi.Property_hasUpdateCallback(self)

    def save(self, fp):
        return _PyIndi.Property_save(self, fp)

    def getNumber(self):
        return _PyIndi.Property_getNumber(self)

    def getText(self):
        return _PyIndi.Property_getText(self)

    def getSwitch(self):
        return _PyIndi.Property_getSwitch(self)

    def getLight(self):
        return _PyIndi.Property_getLight(self)

    def getBLOB(self):
        return _PyIndi.Property_getBLOB(self)

    def __deref__(self, *args):
        return _PyIndi.Property___deref__(self, *args)

    def __ne__(self, arg2):
        return _PyIndi.Property___ne__(self, arg2)

    def __eq__(self, arg2):
        return _PyIndi.Property___eq__(self, arg2)

    def __nonzero__(self):
        return _PyIndi.Property___nonzero__(self)
    __bool__ = __nonzero__



# Register Property in _PyIndi:
_PyIndi.Property_swigregister(Property)
class PropertyBasicText(Property):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _PyIndi.delete_PropertyBasicText

    def setName(self, *args):
        return _PyIndi.PropertyBasicText_setName(self, *args)

    def setLabel(self, *args):
        return _PyIndi.PropertyBasicText_setLabel(self, *args)

    def setGroupName(self, *args):
        return _PyIndi.PropertyBasicText_setGroupName(self, *args)

    def setPermission(self, permission):
        return _PyIndi.PropertyBasicText_setPermission(self, permission)

    def setTimeout(self, timeout):
        return _PyIndi.PropertyBasicText_setTimeout(self, timeout)

    def setState(self, state):
        return _PyIndi.PropertyBasicText_setState(self, state)

    def setTimestamp(self, *args):
        return _PyIndi.PropertyBasicText_setTimestamp(self, *args)

    def getName(self):
        return _PyIndi.PropertyBasicText_getName(self)

    def getLabel(self):
        return _PyIndi.PropertyBasicText_getLabel(self)

    def getGroupName(self):
        return _PyIndi.PropertyBasicText_getGroupName(self)

    def getPermission(self):
        return _PyIndi.PropertyBasicText_getPermission(self)

    def getPermissionAsString(self):
        return _PyIndi.PropertyBasicText_getPermissionAsString(self)

    def getTimeout(self):
        return _PyIndi.PropertyBasicText_getTimeout(self)

    def getState(self):
        return _PyIndi.PropertyBasicText_getState(self)

    def getStateAsString(self):
        return _PyIndi.PropertyBasicText_getStateAsString(self)

    def getTimestamp(self):
        return _PyIndi.PropertyBasicText_getTimestamp(self)

    def isEmpty(self):
        return _PyIndi.PropertyBasicText_isEmpty(self)

    def isNameMatch(self, *args):
        return _PyIndi.PropertyBasicText_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.PropertyBasicText_isLabelMatch(self, *args)

    def save(self, f):
        return _PyIndi.PropertyBasicText_save(self, f)

    def __and__(self):
        return _PyIndi.PropertyBasicText___and__(self)

    def size(self):
        return _PyIndi.PropertyBasicText_size(self)

    def reserve(self, size):
        return _PyIndi.PropertyBasicText_reserve(self, size)

    def resize(self, size):
        return _PyIndi.PropertyBasicText_resize(self, size)

    def shrink_to_fit(self):
        return _PyIndi.PropertyBasicText_shrink_to_fit(self)

    def push(self, *args):
        return _PyIndi.PropertyBasicText_push(self, *args)

    def at(self, index):
        return _PyIndi.PropertyBasicText_at(self, index)

    def begin(self, *args):
        return _PyIndi.PropertyBasicText_begin(self, *args)

    def end(self, *args):
        return _PyIndi.PropertyBasicText_end(self, *args)

    def findWidgetByName(self, name):
        return _PyIndi.PropertyBasicText_findWidgetByName(self, name)

    def findWidgetIndexByName(self, name):
        return _PyIndi.PropertyBasicText_findWidgetIndexByName(self, name)

    def __ref__(self):
        return _PyIndi.PropertyBasicText___ref__(self)

    def __getitem__(self, index):
        return _PyIndi.PropertyBasicText___getitem__(self, index)

    def __len__(self):
        return _PyIndi.PropertyBasicText___len__(self)

# Register PropertyBasicText in _PyIndi:
_PyIndi.PropertyBasicText_swigregister(PropertyBasicText)
class PropertyBasicNumber(Property):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _PyIndi.delete_PropertyBasicNumber

    def setName(self, *args):
        return _PyIndi.PropertyBasicNumber_setName(self, *args)

    def setLabel(self, *args):
        return _PyIndi.PropertyBasicNumber_setLabel(self, *args)

    def setGroupName(self, *args):
        return _PyIndi.PropertyBasicNumber_setGroupName(self, *args)

    def setPermission(self, permission):
        return _PyIndi.PropertyBasicNumber_setPermission(self, permission)

    def setTimeout(self, timeout):
        return _PyIndi.PropertyBasicNumber_setTimeout(self, timeout)

    def setState(self, state):
        return _PyIndi.PropertyBasicNumber_setState(self, state)

    def setTimestamp(self, *args):
        return _PyIndi.PropertyBasicNumber_setTimestamp(self, *args)

    def getName(self):
        return _PyIndi.PropertyBasicNumber_getName(self)

    def getLabel(self):
        return _PyIndi.PropertyBasicNumber_getLabel(self)

    def getGroupName(self):
        return _PyIndi.PropertyBasicNumber_getGroupName(self)

    def getPermission(self):
        return _PyIndi.PropertyBasicNumber_getPermission(self)

    def getPermissionAsString(self):
        return _PyIndi.PropertyBasicNumber_getPermissionAsString(self)

    def getTimeout(self):
        return _PyIndi.PropertyBasicNumber_getTimeout(self)

    def getState(self):
        return _PyIndi.PropertyBasicNumber_getState(self)

    def getStateAsString(self):
        return _PyIndi.PropertyBasicNumber_getStateAsString(self)

    def getTimestamp(self):
        return _PyIndi.PropertyBasicNumber_getTimestamp(self)

    def isEmpty(self):
        return _PyIndi.PropertyBasicNumber_isEmpty(self)

    def isNameMatch(self, *args):
        return _PyIndi.PropertyBasicNumber_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.PropertyBasicNumber_isLabelMatch(self, *args)

    def save(self, f):
        return _PyIndi.PropertyBasicNumber_save(self, f)

    def __and__(self):
        return _PyIndi.PropertyBasicNumber___and__(self)

    def size(self):
        return _PyIndi.PropertyBasicNumber_size(self)

    def reserve(self, size):
        return _PyIndi.PropertyBasicNumber_reserve(self, size)

    def resize(self, size):
        return _PyIndi.PropertyBasicNumber_resize(self, size)

    def shrink_to_fit(self):
        return _PyIndi.PropertyBasicNumber_shrink_to_fit(self)

    def push(self, *args):
        return _PyIndi.PropertyBasicNumber_push(self, *args)

    def at(self, index):
        return _PyIndi.PropertyBasicNumber_at(self, index)

    def begin(self, *args):
        return _PyIndi.PropertyBasicNumber_begin(self, *args)

    def end(self, *args):
        return _PyIndi.PropertyBasicNumber_end(self, *args)

    def findWidgetByName(self, name):
        return _PyIndi.PropertyBasicNumber_findWidgetByName(self, name)

    def findWidgetIndexByName(self, name):
        return _PyIndi.PropertyBasicNumber_findWidgetIndexByName(self, name)

    def __ref__(self):
        return _PyIndi.PropertyBasicNumber___ref__(self)

    def __getitem__(self, index):
        return _PyIndi.PropertyBasicNumber___getitem__(self, index)

    def __len__(self):
        return _PyIndi.PropertyBasicNumber___len__(self)

# Register PropertyBasicNumber in _PyIndi:
_PyIndi.PropertyBasicNumber_swigregister(PropertyBasicNumber)
class PropertyBasicSwitch(Property):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _PyIndi.delete_PropertyBasicSwitch

    def setName(self, *args):
        return _PyIndi.PropertyBasicSwitch_setName(self, *args)

    def setLabel(self, *args):
        return _PyIndi.PropertyBasicSwitch_setLabel(self, *args)

    def setGroupName(self, *args):
        return _PyIndi.PropertyBasicSwitch_setGroupName(self, *args)

    def setPermission(self, permission):
        return _PyIndi.PropertyBasicSwitch_setPermission(self, permission)

    def setTimeout(self, timeout):
        return _PyIndi.PropertyBasicSwitch_setTimeout(self, timeout)

    def setState(self, state):
        return _PyIndi.PropertyBasicSwitch_setState(self, state)

    def setTimestamp(self, *args):
        return _PyIndi.PropertyBasicSwitch_setTimestamp(self, *args)

    def getName(self):
        return _PyIndi.PropertyBasicSwitch_getName(self)

    def getLabel(self):
        return _PyIndi.PropertyBasicSwitch_getLabel(self)

    def getGroupName(self):
        return _PyIndi.PropertyBasicSwitch_getGroupName(self)

    def getPermission(self):
        return _PyIndi.PropertyBasicSwitch_getPermission(self)

    def getPermissionAsString(self):
        return _PyIndi.PropertyBasicSwitch_getPermissionAsString(self)

    def getTimeout(self):
        return _PyIndi.PropertyBasicSwitch_getTimeout(self)

    def getState(self):
        return _PyIndi.PropertyBasicSwitch_getState(self)

    def getStateAsString(self):
        return _PyIndi.PropertyBasicSwitch_getStateAsString(self)

    def getTimestamp(self):
        return _PyIndi.PropertyBasicSwitch_getTimestamp(self)

    def isEmpty(self):
        return _PyIndi.PropertyBasicSwitch_isEmpty(self)

    def isNameMatch(self, *args):
        return _PyIndi.PropertyBasicSwitch_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.PropertyBasicSwitch_isLabelMatch(self, *args)

    def save(self, f):
        return _PyIndi.PropertyBasicSwitch_save(self, f)

    def __and__(self):
        return _PyIndi.PropertyBasicSwitch___and__(self)

    def size(self):
        return _PyIndi.PropertyBasicSwitch_size(self)

    def reserve(self, size):
        return _PyIndi.PropertyBasicSwitch_reserve(self, size)

    def resize(self, size):
        return _PyIndi.PropertyBasicSwitch_resize(self, size)

    def shrink_to_fit(self):
        return _PyIndi.PropertyBasicSwitch_shrink_to_fit(self)

    def push(self, *args):
        return _PyIndi.PropertyBasicSwitch_push(self, *args)

    def at(self, index):
        return _PyIndi.PropertyBasicSwitch_at(self, index)

    def begin(self, *args):
        return _PyIndi.PropertyBasicSwitch_begin(self, *args)

    def end(self, *args):
        return _PyIndi.PropertyBasicSwitch_end(self, *args)

    def findWidgetByName(self, name):
        return _PyIndi.PropertyBasicSwitch_findWidgetByName(self, name)

    def findWidgetIndexByName(self, name):
        return _PyIndi.PropertyBasicSwitch_findWidgetIndexByName(self, name)

    def __ref__(self):
        return _PyIndi.PropertyBasicSwitch___ref__(self)

    def __getitem__(self, index):
        return _PyIndi.PropertyBasicSwitch___getitem__(self, index)

    def __len__(self):
        return _PyIndi.PropertyBasicSwitch___len__(self)

# Register PropertyBasicSwitch in _PyIndi:
_PyIndi.PropertyBasicSwitch_swigregister(PropertyBasicSwitch)
class PropertyBasicLight(Property):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _PyIndi.delete_PropertyBasicLight

    def setName(self, *args):
        return _PyIndi.PropertyBasicLight_setName(self, *args)

    def setLabel(self, *args):
        return _PyIndi.PropertyBasicLight_setLabel(self, *args)

    def setGroupName(self, *args):
        return _PyIndi.PropertyBasicLight_setGroupName(self, *args)

    def setPermission(self, permission):
        return _PyIndi.PropertyBasicLight_setPermission(self, permission)

    def setTimeout(self, timeout):
        return _PyIndi.PropertyBasicLight_setTimeout(self, timeout)

    def setState(self, state):
        return _PyIndi.PropertyBasicLight_setState(self, state)

    def setTimestamp(self, *args):
        return _PyIndi.PropertyBasicLight_setTimestamp(self, *args)

    def getName(self):
        return _PyIndi.PropertyBasicLight_getName(self)

    def getLabel(self):
        return _PyIndi.PropertyBasicLight_getLabel(self)

    def getGroupName(self):
        return _PyIndi.PropertyBasicLight_getGroupName(self)

    def getPermission(self):
        return _PyIndi.PropertyBasicLight_getPermission(self)

    def getPermissionAsString(self):
        return _PyIndi.PropertyBasicLight_getPermissionAsString(self)

    def getTimeout(self):
        return _PyIndi.PropertyBasicLight_getTimeout(self)

    def getState(self):
        return _PyIndi.PropertyBasicLight_getState(self)

    def getStateAsString(self):
        return _PyIndi.PropertyBasicLight_getStateAsString(self)

    def getTimestamp(self):
        return _PyIndi.PropertyBasicLight_getTimestamp(self)

    def isEmpty(self):
        return _PyIndi.PropertyBasicLight_isEmpty(self)

    def isNameMatch(self, *args):
        return _PyIndi.PropertyBasicLight_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.PropertyBasicLight_isLabelMatch(self, *args)

    def save(self, f):
        return _PyIndi.PropertyBasicLight_save(self, f)

    def __and__(self):
        return _PyIndi.PropertyBasicLight___and__(self)

    def size(self):
        return _PyIndi.PropertyBasicLight_size(self)

    def reserve(self, size):
        return _PyIndi.PropertyBasicLight_reserve(self, size)

    def resize(self, size):
        return _PyIndi.PropertyBasicLight_resize(self, size)

    def shrink_to_fit(self):
        return _PyIndi.PropertyBasicLight_shrink_to_fit(self)

    def push(self, *args):
        return _PyIndi.PropertyBasicLight_push(self, *args)

    def at(self, index):
        return _PyIndi.PropertyBasicLight_at(self, index)

    def begin(self, *args):
        return _PyIndi.PropertyBasicLight_begin(self, *args)

    def end(self, *args):
        return _PyIndi.PropertyBasicLight_end(self, *args)

    def findWidgetByName(self, name):
        return _PyIndi.PropertyBasicLight_findWidgetByName(self, name)

    def findWidgetIndexByName(self, name):
        return _PyIndi.PropertyBasicLight_findWidgetIndexByName(self, name)

    def __ref__(self):
        return _PyIndi.PropertyBasicLight___ref__(self)

    def __getitem__(self, index):
        return _PyIndi.PropertyBasicLight___getitem__(self, index)

    def __len__(self):
        return _PyIndi.PropertyBasicLight___len__(self)

# Register PropertyBasicLight in _PyIndi:
_PyIndi.PropertyBasicLight_swigregister(PropertyBasicLight)
class PropertyBasicBlob(Property):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _PyIndi.delete_PropertyBasicBlob

    def setName(self, *args):
        return _PyIndi.PropertyBasicBlob_setName(self, *args)

    def setLabel(self, *args):
        return _PyIndi.PropertyBasicBlob_setLabel(self, *args)

    def setGroupName(self, *args):
        return _PyIndi.PropertyBasicBlob_setGroupName(self, *args)

    def setPermission(self, permission):
        return _PyIndi.PropertyBasicBlob_setPermission(self, permission)

    def setTimeout(self, timeout):
        return _PyIndi.PropertyBasicBlob_setTimeout(self, timeout)

    def setState(self, state):
        return _PyIndi.PropertyBasicBlob_setState(self, state)

    def setTimestamp(self, *args):
        return _PyIndi.PropertyBasicBlob_setTimestamp(self, *args)

    def getName(self):
        return _PyIndi.PropertyBasicBlob_getName(self)

    def getLabel(self):
        return _PyIndi.PropertyBasicBlob_getLabel(self)

    def getGroupName(self):
        return _PyIndi.PropertyBasicBlob_getGroupName(self)

    def getPermission(self):
        return _PyIndi.PropertyBasicBlob_getPermission(self)

    def getPermissionAsString(self):
        return _PyIndi.PropertyBasicBlob_getPermissionAsString(self)

    def getTimeout(self):
        return _PyIndi.PropertyBasicBlob_getTimeout(self)

    def getState(self):
        return _PyIndi.PropertyBasicBlob_getState(self)

    def getStateAsString(self):
        return _PyIndi.PropertyBasicBlob_getStateAsString(self)

    def getTimestamp(self):
        return _PyIndi.PropertyBasicBlob_getTimestamp(self)

    def isEmpty(self):
        return _PyIndi.PropertyBasicBlob_isEmpty(self)

    def isNameMatch(self, *args):
        return _PyIndi.PropertyBasicBlob_isNameMatch(self, *args)

    def isLabelMatch(self, *args):
        return _PyIndi.PropertyBasicBlob_isLabelMatch(self, *args)

    def save(self, f):
        return _PyIndi.PropertyBasicBlob_save(self, f)

    def __and__(self):
        return _PyIndi.PropertyBasicBlob___and__(self)

    def size(self):
        return _PyIndi.PropertyBasicBlob_size(self)

    def reserve(self, size):
        return _PyIndi.PropertyBasicBlob_reserve(self, size)

    def resize(self, size):
        return _PyIndi.PropertyBasicBlob_resize(self, size)

    def shrink_to_fit(self):
        return _PyIndi.PropertyBasicBlob_shrink_to_fit(self)

    def push(self, *args):
        return _PyIndi.PropertyBasicBlob_push(self, *args)

    def at(self, index):
        return _PyIndi.PropertyBasicBlob_at(self, index)

    def begin(self, *args):
        return _PyIndi.PropertyBasicBlob_begin(self, *args)

    def end(self, *args):
        return _PyIndi.PropertyBasicBlob_end(self, *args)

    def findWidgetByName(self, name):
        return _PyIndi.PropertyBasicBlob_findWidgetByName(self, name)

    def findWidgetIndexByName(self, name):
        return _PyIndi.PropertyBasicBlob_findWidgetIndexByName(self, name)

    def __ref__(self):
        return _PyIndi.PropertyBasicBlob___ref__(self)

    def __getitem__(self, index):
        return _PyIndi.PropertyBasicBlob___getitem__(self, index)

    def __len__(self):
        return _PyIndi.PropertyBasicBlob___len__(self)

# Register PropertyBasicBlob in _PyIndi:
_PyIndi.PropertyBasicBlob_swigregister(PropertyBasicBlob)
class PropertyText(PropertyBasicText):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _PyIndi.PropertyText_swiginit(self, _PyIndi.new_PropertyText(*args))
    __swig_destroy__ = _PyIndi.delete_PropertyText

    def update(self, texts, names, n):
        return _PyIndi.PropertyText_update(self, texts, names, n)

    def fill(self, device, name, label, group, permission, timeout, state):
        return _PyIndi.PropertyText_fill(self, device, name, label, group, permission, timeout, state)

# Register PropertyText in _PyIndi:
_PyIndi.PropertyText_swigregister(PropertyText)
class PropertyNumber(PropertyBasicNumber):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _PyIndi.PropertyNumber_swiginit(self, _PyIndi.new_PropertyNumber(*args))
    __swig_destroy__ = _PyIndi.delete_PropertyNumber

    def update(self, values, names, n):
        return _PyIndi.PropertyNumber_update(self, values, names, n)

    def fill(self, device, name, label, group, permission, timeout, state):
        return _PyIndi.PropertyNumber_fill(self, device, name, label, group, permission, timeout, state)

    def updateMinMax(self):
        return _PyIndi.PropertyNumber_updateMinMax(self)

# Register PropertyNumber in _PyIndi:
_PyIndi.PropertyNumber_swigregister(PropertyNumber)
class PropertySwitch(PropertyBasicSwitch):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _PyIndi.PropertySwitch_swiginit(self, _PyIndi.new_PropertySwitch(*args))
    __swig_destroy__ = _PyIndi.delete_PropertySwitch

    def onNewValues(self, callback):
        return _PyIndi.PropertySwitch_onNewValues(self, callback)

    def update(self, states, names, n):
        return _PyIndi.PropertySwitch_update(self, states, names, n)

    def hasUpdateCallback(self):
        return _PyIndi.PropertySwitch_hasUpdateCallback(self)

    def fill(self, device, name, label, group, permission, rule, timeout, state):
        return _PyIndi.PropertySwitch_fill(self, device, name, label, group, permission, rule, timeout, state)

    def reset(self):
        return _PyIndi.PropertySwitch_reset(self)

    def findOnSwitchIndex(self):
        return _PyIndi.PropertySwitch_findOnSwitchIndex(self)

    def findOnSwitch(self):
        return _PyIndi.PropertySwitch_findOnSwitch(self)

    def setRule(self, rule):
        return _PyIndi.PropertySwitch_setRule(self, rule)

    def getRule(self):
        return _PyIndi.PropertySwitch_getRule(self)

    def getRuleAsString(self):
        return _PyIndi.PropertySwitch_getRuleAsString(self)

# Register PropertySwitch in _PyIndi:
_PyIndi.PropertySwitch_swigregister(PropertySwitch)
class PropertyLight(PropertyBasicLight):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _PyIndi.PropertyLight_swiginit(self, _PyIndi.new_PropertyLight(*args))
    __swig_destroy__ = _PyIndi.delete_PropertyLight

    def fill(self, device, name, label, group, state):
        return _PyIndi.PropertyLight_fill(self, device, name, label, group, state)

# Register PropertyLight in _PyIndi:
_PyIndi.PropertyLight_swigregister(PropertyLight)
class PropertyBlob(PropertyBasicBlob):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _PyIndi.PropertyBlob_swiginit(self, _PyIndi.new_PropertyBlob(*args))
    __swig_destroy__ = _PyIndi.delete_PropertyBlob

    def update(self, sizes, blobsizes, blobs, formats, names, n):
        return _PyIndi.PropertyBlob_update(self, sizes, blobsizes, blobs, formats, names, n)

    def fill(self, device, name, label, group, permission, timeout, state):
        return _PyIndi.PropertyBlob_fill(self, device, name, label, group, permission, timeout, state)

# Register PropertyBlob in _PyIndi:
_PyIndi.PropertyBlob_swigregister(PropertyBlob)
B_NEVER = _PyIndi.B_NEVER
B_ALSO = _PyIndi.B_ALSO
B_ONLY = _PyIndi.B_ONLY
class Properties(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _PyIndi.Properties_swiginit(self, _PyIndi.new_Properties())
    __swig_destroy__ = _PyIndi.delete_Properties

    def push_back(self, *args):
        return _PyIndi.Properties_push_back(self, *args)

    def clear(self):
        return _PyIndi.Properties_clear(self)

    def size(self):
        return _PyIndi.Properties_size(self)

    def begin(self, *args):
        return _PyIndi.Properties_begin(self, *args)

    def end(self, *args):
        return _PyIndi.Properties_end(self, *args)

    def erase(self, *args):
        return _PyIndi.Properties_erase(self, *args)

    def __ref__(self, *args):
        return _PyIndi.Properties___ref__(self, *args)

    def __deref__(self, *args):
        return _PyIndi.Properties___deref__(self, *args)

    def __getitem__(self, index):
        return _PyIndi.Properties___getitem__(self, index)

    def __len__(self):
        return _PyIndi.Properties___len__(self)

# Register Properties in _PyIndi:
_PyIndi.Properties_swigregister(Properties)

